name: CI Build for Eduvacity-FRONTEND

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build --build-arg STRIPE_PUBLIC_KEY=${{secrets.STRIPE_PUBLIC_KEY}} -t eduv/eduvacity-frontend:latest .

      - name: Docker Push
        run: docker push eduv/eduvacity-frontend:latest

      - name: Docker Push
        run: docker push eduv/eduvacity-frontend:latest

      - name: Sign in to Droplet and execute commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DROPLET_HOST}}
          username: abdulreal
          password: ${{secrets.DROPLET_PASSWORD}}
          script: |
            docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }} 
            docker stop eduvacity-frontend
            docker rm eduvacity-frontend
            docker rmi eduv/eduvacity-frontend:latest
            docker pull eduv/eduvacity-frontend:latest
            docker run -d  -p 3001:3000 \
            --restart always \
            --name eduvacity-frontend \
            eduv/eduvacity-frontend:latest

       # Notify Slack on success
      - name: Slack Notification on Success
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          channel: development
          text: "✅ Workflow Succeeded: ${{ github.workflow }} on branch ${{ github.ref }} by ${{ github.actor }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      # Notify Slack on failure
      - name: Slack Notification on Failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          channel: development
          text: "❌ Workflow Failed: ${{ github.workflow }} on branch ${{ github.ref }} by ${{ github.actor }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

